[project]
name = "call-me-maybe"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0",
    "numpy>=1.26",
    "torch>=2.13.0",
    "transformers>=5.15.1",
    "huggingface-hub>=1.28.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]
